### ISSUE TITLE
Ice Cards

### ISSUE THREAD

**Issue by jubae** [coldmix/windower-lua-add-ons#2]
Hi,

Firstly GREAT addon!  One issue I am having is getting this to work with Ice cards. Basically it just doesn't seem to do anything. When the other cards drop into my inventory, it triggers and kicks in and is amazing. However, Ice Cards simply don't trigger anything and no matter what I try, I jsut cant get them to work?!

I have the correct names in the recipe lists for both this and also the "Craft" addon as well as correctly added to the main Lua for this addon also. Like I say, it works perfectly for all the cards, but the Ice Cards just wont trigger it at all. Just wondered if you had any ideas?

Thanks you in advance for any assistance!

**Comment by coldmix** [comment]
I have not been able to work on it since i have finished shield.

Frankly, for cards, you shouldn't synth them while farming since they are stackable. It would be more efficient to farm a big stack and craft them in the guild with synthesis support and food. You should be able to craft them in bulk using the craft plugin alone.
